CREATE TABLE productos
(
	ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(ID),
    NOMBRE CHAR(90),
    CANTIDAD_PRODUCTOS INT(5)
)

CREATE TABLE  productos2
(
	   ID INT NOT NULL AUTO_INCREMENT,
	    PRIMARY KEY(ID),
	    NOMBRE CHAR(90),
	CANTIDAD_PRODUCTOS INT(5)
)

DELIMITER //
CREATE TRIGGER INSERTAR_PRODUCTOS2 AFTER INSERT ON productos
	FOR EACH ROW
    	BEGIN
        	INSERT INTO productos2
        	SET productos2.CANTIDAD_PRODUCTOS = NEW.CANTIDAD_PRODUCTOS,productos2.NOMBRE = CONCAT(NEW.NOMBRE," PRODUCTO2");
        END
//

DELIMITER //
CREATE TRIGGER ELIMINAR_PRODUCTOS2 AFTER DELETE ON productos
	FOR EACH ROW
    	BEGIN
        	DELETE FROM productos2 WHERE productos2.NOMBRE = CONCAT(OLD.NOMBRE," PRODUCTO2");
        END
//

DELIMITER //
CREATE TRIGGER ACTUALIZAR_PRODUCTOS2 AFTER UPDATE ON productos
	FOR EACH ROW
    	BEGIN
        	UPDATE productos2
            SET productos2.CANTIDAD_PRODUCTOS = NEW.CANTIDAD_PRODUCTOS - 1
            WHERE productos2.CANTIDAD_PRODUCTOS = OLD.CANTIDAD_PRODUCTOS;
        END
//
