DELIMITER //
CREATE PROCEDURE DECREMENTAR_CANT_PRODUCTOS(NOMBRE_PRODUCTO VARCHAR(40))
	BEGIN
    	#DECLARO UNA VARIABLE CANT_PRODUCTO Y LA INICIALIZO CON LA CANTIDAD DE PRODUCTOS DEL PRODUCTO QUE ESTA ALMACENADO EN EL PARAMETRO NOMBRE_PRODUCTO.
    	DECLARE CANT_PRODUCTO INT(9) DEFAULT (SELECT productos.CANTIDAD_PRODUCTOS FROM productos WHERE productos.NOMBRE = NOMBRE_PRODUCTO);
        
        #DECLARO OTRA VARIABLE, PERO ESTA NO ESTA INICIALIZADA. TIENE UN VALOR NULO 
    	DECLARE ID_PRODUCTO INT(9);
        #SI LA CATIDAD DEL PRODUCTO ES MAYOR QUE CERO 
        IF CANT_PRODUCTO > 0 THEN
        	#A ID_PRODUCTO LE ASIGNO LA ID DEL PRODUCTO INGRESADO
        	SET ID_PRODUCTO = (SELECT productos.ID FROM productos WHERE productos.NOMBRE = NOMBRE_PRODUCTO);
            #ACTUALIZAMOS LA CANTIDAD DE PRODUCTOS
        	UPDATE productos
            SET productos.CANTIDAD_PRODUCTOS = CANT_PRODUCTO -1
            WHERE productos.ID = ID_PRODUCTO AND productos.NOMBRE = NOMBRE_PRODUCTO;
        END IF;
    END
//